### ISSUE TITLE
rethink version numbers

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#204]
The way we are using version numbers seems odd. Only the middle semver number is ever used, and we currently do not allow model authors to be able to specify the version number explicitly. Perhaps we should go back to the old simple incremental number approach?

**Comment by alee** [comment]
Alternatively we should add some code + logic to allow model authors to specify what kind of change is being made to the model (major, minor, patch) and increment the semver number appropriately automatically.

**Comment by alee** [comment]
Two tasks:

1. Add UI to set the version number explicitly (with validation logic, version number can't be "less" than previous one). This could get thorny if we allow arbitrary version numbering systems so I think we should stick with [semver](http://semver.org) if possible and link to it for more info
2. Add UI to signify what kind of change the given release is (only for updates to a given model, major / minor / patch).

@cpritcha can you take a stab at this?

**Comment by cpritcha** [comment]
Right now a release is created (with a version number) as soon as soon as a codebase is created and the user requests a draft. Since the version number is part of the url we would need to move draft releases to a new set of urls.

How I think it would work:

- When a release is unpublished the edit view would force you to set a version number before publishing the release (in the publish modal).
- The version number field on CodebaseRelease model would be nullable
- Draft releases would use the identifier field or a uuid field for its urls

**Comment by alee** [comment]
Good points. I think switching to an internal / explicit identifier field for the release URL edit page is a good idea if we want to allow the version number to be mutable. 

We can still automatically set the version number on the draft release, but let it be customizable so submitters can change it before they publish. You'll need to run some validation logic to ensure that the version number being set is after the most recent version number (and bypassed on fresh releases). The [https://pypi.python.org/pypi/semver](python semver) library can do this on the back end but you might want to pull in https://www.npmjs.com/package/semver for front end validation

**Comment by cpritcha** [comment]
That sounds better. I'll keep the version number field the way it is but change the edit urls to use a unique immutable value.

**Comment by alee** [comment]
patched in 5682b3d942b941a031d4a86c83d0e267e0faf461
